old_sound_rabbit_mq:
    connections:
        default:
            host: '%env(RABBITMQ_HOST)%'
            port: '%env(RABBITMQ_PORT)%'
            user: '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost: /
            lazy: true
    producers:
        analytics:
            connection: default
            exchange_options: { name: analytics, type: topic }