version: '3'

x-app: &app
  build:
    context: .
    args:
      UID: ${UID}
      GID: ${GID}
  env_file:
    - docker-compose.env
  environment:
    PHP_CLI_MEMORY_LIMIT: "1024M"
    COMPOSER_HOME: ".composer"
  ports:
    - "4500:8080"
  volumes:
    - ./:/var/www/app
  restart: on-failure

services:
  app:
    <<: *app
    command: ["rr", "serve", "-c", ".rr.dev.yaml"]

  xdebug:
    <<: *app
    command: ["rr", "serve", "-c", ".rr.dev.yaml"]
    profiles: ["xdebug"]
    env_file:
      - docker-compose.env
      - .env.xdebug
    extra_hosts:
      # https://stackoverflow.com/a/67158212
      # only works with Docker v20.10+
      - "host.docker.internal:host-gateway"

  test:
    <<: *app
    command: ["composer", "run", "test"]
    profiles:
      - test
    env_file:
      - docker-compose.env
      - .env.test
